/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockJournalRouteImport } from './routes/UnlockJournal'
import { Route as CreateJournalRouteImport } from './routes/CreateJournal'
import { Route as IndexRouteImport } from './routes/index'

const UnlockJournalRoute = UnlockJournalRouteImport.update({
  id: '/UnlockJournal',
  path: '/UnlockJournal',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateJournalRoute = CreateJournalRouteImport.update({
  id: '/CreateJournal',
  path: '/CreateJournal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/CreateJournal': typeof CreateJournalRoute
  '/UnlockJournal': typeof UnlockJournalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/CreateJournal': typeof CreateJournalRoute
  '/UnlockJournal': typeof UnlockJournalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/CreateJournal': typeof CreateJournalRoute
  '/UnlockJournal': typeof UnlockJournalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/CreateJournal' | '/UnlockJournal'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/CreateJournal' | '/UnlockJournal'
  id: '__root__' | '/' | '/CreateJournal' | '/UnlockJournal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateJournalRoute: typeof CreateJournalRoute
  UnlockJournalRoute: typeof UnlockJournalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/UnlockJournal': {
      id: '/UnlockJournal'
      path: '/UnlockJournal'
      fullPath: '/UnlockJournal'
      preLoaderRoute: typeof UnlockJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/CreateJournal': {
      id: '/CreateJournal'
      path: '/CreateJournal'
      fullPath: '/CreateJournal'
      preLoaderRoute: typeof CreateJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateJournalRoute: CreateJournalRoute,
  UnlockJournalRoute: UnlockJournalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
